	$(document).ready(function(){
		$('.twitter-feed').list_ticker({
			speed:5000,
			effect:'fade'
		});	
		$('.ticker').list_ticker({
			speed:5000,
			effect:'fade'
		});	
		$('.ticker-image').list_ticker({
			speed:5000,
			effect:'fade'
		});	
	})